**3. You are about to start a new python based project? What kind of structure would you use?**

In general Python provides diverse options, the first step is to understand my project demands, or what the project is about and its complexity. As beginner on python, I would go with the flat style for my project layout rather than src. I will choose the dependencies requirements, then I will do packaging and modules, and then create a single script (.py or .ipynb). Then I will do the essential imports, and perform all the steps to carry my project.

*Reference:*
1.	 (https://medium.com/@joshuale/a-practical-guide-to-python-project-structure-and-packaging-90c7f7a04f95). 
2.	https://dev.to/codemouse92/dead-simple-python-project-structure-and-imports-38c6 
3.	(https://discuss.python.org/t/python-project-structure/36119/2).


**5. What are complex systems? What is a network? How does the Game of life work?**
A complex system is a system that has interacting components, and these components emerges as behaviors, and the behavior cannot be predict by studying single component. The example includes human brain, complex software and electronic system, organisms etc. 
 Network is a collection of interacting entities or objects. These objects, called nodes, are linked together by connections, also known as edges. Networks can represent various relationships, such as physical connections, information flow, or social interactions.
It's a simple set of rules applied to a grid of cells, but it can exhibit surprisingly complex behavior. The grid is made up of cells, which can be either alive (represented by black) or dead (represented by white). The evolution of the system is determined by four basic rules: A live cell with fewer than two live neighbors dies in the next generation (underpopulation). A live cell with two or three live neighbors lives on to the next generation. A dead cell with exactly three live neighbors becomes a live cell in the next generation (reproduction). All other dead cells (with zero, one, or four or more live neighbors) stay dead in the next generation. The Game of Life can create a variety of interesting patterns, some of which can grow or change shape over time. It's an example of a complex system that emerges from simple rules.
*Reference:*
1.	https://en.wikipedia.org/wiki/Complex_system#References
2.	https://www.hasbro.com/common/instruct/Life,_the_game_of_%281991%29.pdf ; https://youtu.be/S-W0NX97DB0?si=XonyVeAFs__bScKd
3.	https://en.wikipedia.org/wiki/Biological_network
4.	Lecture one 
 


**11. What is data? What are data stuctures? Why do we need structured data? What is the dataclass in python?**
In common usage, data is a collection of discrete or continuous values that convey information, describing the quantity, quality, fact, statistics, other basic units of meaning, or simply sequences of symbols that may be further interpreted formally.
Data is an information that describe the quantity, quality, fact, statistics, other basic units of meaning, or simply sequences of symbols that may be further interpreted formally in a particular format. 
Data structure is way to organize a data so that it can be accessed efficiently, a data can be integer, string, float or Boolean. The data structures in python are divided as mutable and immutable. Mutable consist of list, dictionaries and sets, while immutable is tuple which is a built in data structure. We need data structure to access the data effectively, for example we use list to store sequence of items where we can modify elements based on position. Tuples store fixed data, dictionaries used for storing and retrieving data based on unique keys, and Sets are useful for checking membership (if an item exists in the collection) or removing duplicates from a list. 
Dataclass is just used to store data (information) that flow between parts of a program or a system. Creating data classes in Python can be tedious, especially writing the __init__ method every time. The dataclasses module (available since Python 3.7) simplifies this process. With dataclasses, we can create data classes in just a few lines without manually writing methods like __init__. These classes automatically come with essential methods li__ __init__ to handle data initialization, making the code cleaner and less error-pron

*Reference:*
1.	https://www.simplilearn.com/what-is-data-article  
2.	https://en.wikipedia.org/wiki/Data
3.	https://www.dataquest.io/blog/data-structures-in-python/ . https://docs.python.org/3/tutorial/datastructures.html
4.	https://www.dataquest.io/blog/how-to-use-python-data-classes/
e. 



**16. DNA is text, and human language is also text. How is parsing of DNA different from parsing of human language? Which python module would you ue to pars DNA?**DNA parsing uses simpler alphabet as DNA uses a 4-letter alphabet (A, C, G, T) representing nucleotides. While Languages have a much larger alphabet with letters, punctuation, and special characters. Further, the DNA parsing involve the identification of patterns like genes or regulatory elements within sequence. While human language involves understanding the meaning conveyed by the words and sentence structure. For DNA parsing in python, we Import Biopython library for DNA parsing. But for human language we Import library for Natural Language Processing (NLTK). I will use Biopython library for DNA parsing, and then I will use SeqIO from BIO to find the specific patterns in the genes. Like mentioned in the bio python tutorials.

*References:*
1.	https://www.cs.cornell.edu/courses/cs2110/2010fa/assignments/a1/doc/cs2110/assignment1/DNAParser.html
2.	https://opensource.com/article/20/8/intro-python-nltk
3.	https://pieriantraining.com/parsing-data-in-python-a-tutorial-for-beginners/#:~:text=Parsing%20data%20in%20Python%20involves,analysis%2C%20and%20natural%20language%20processing.
4.	https://biopython.org/DIST/docs/tutorial/Tutorial.
5.	https://youtu.be/2SVPRm574ow?si=b2vAA7kCBXTWjGks
   tml 



In [1]:
#Question16
pip install biopython

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330


In [24]:
from Bio import SeqIO
record = SeqIO.read("out1.fna", "fasta")


In [25]:
dna_sequence = str(record.seq)
mydna = str(record.seq)


In [27]:
#function to find a specific gene pattern 
def find_gene(mydna, gene_pattern):
  start = 0
  genes = []
  while True:
    # Search for the gene pattern starting from the current position
    index = mydna.find(gene_pattern, start)
    if index == -1:
      break  # No more occurrences found
    genes.append((start, index + len(gene_pattern)))  # Record gene location
    start = index + 1  # Move search start position 
gene_pattern = "AATCTTTTAATCTTTAAACGTGTT"
genes = find_gene(mydna, gene_pattern)
# Print the locations of the found genes
if genes:
  for start, end in genes:
    print(f"Gene found between positions {start} and {end}")
else:
  print("No genes found with the specified pattern") 


No genes found with the specified pattern


**18. What is the difference between structured, unstructured and semi-structured data. What kind of data do you think is the most common in this world?**
Structured data is stored in a predefined format and is highly specific; whereas unstructured data is a collection of many varied data types that are stored in their native formats; while semi-structured data does not follow the tabular data structure models associated with relational databases or other data table forms. Each type has its own pros and cons, structure data less processing and easier to manage but limited usability due pre-defined structure. Unstructured data has variety of native formats facilitates a greater number of use cases and applications but the greater number of formats makes it equally challenging to analyze and leverage unstructured data. While Semi structure use information that does not reside in a relational database but that has some organizational properties that make it easier to analyze. In my opinion, the world so messy so the unstructured data must be in common because information come in many forms, not just neat rows and columns. 

*Reference:*
1.	https://www.geeksforgeeks.org/difference-between-structured-semi-structured-and-unstructured-data/
2.	https://k21academy.com/microsoft-azure/dp-900/structured-data-vs-unstructured-data-vs-semi-structured-data/#:~:text=Structured%20data%20is%20stored%20in,databases%20or%20other%20data%20table


**21. What is the difference between t-statistics, and p value? What is r-squared?**
The t-value is a way to quantify the difference between the population means. While P-value is a measure of the probability of an observation lying at extreme t-values. Larger t-value indicates high difference between means, but it does not tell how significance is the difference. And lower p-value suggests the observed difference between the means is less likely due to chance and may be statistically significant. R-squared measure the proportion of the variance for a dependent variable that’s predictable from the independent variable(s).

*References*

1.	https://analyticsindiamag.com/understand-the-significance-of-t-test-and-p-value-using-python/#:~:text=The%20t%2Dstatistic%20is%20a,value%20also%20implies%20%E2%80%9Csignificance%E2%80%9D.
2.	https://analyticsindiamag.com/understand-the-significance-of-t-test-and-p-value-using-python/#:~:text=The%20t%2Dstatistic%20is%20a,value%20also%20implies%20%E2%80%9Csignificance%E2%80%9D.
3.	 https://en.wikipedia.org/wiki/Coefficient_of_determination
4.	https://www.investopedia.com/terms/r/r-squared.asp


**31. What is a simplex? What is a PCA? What does it mean to perform a dimensionality reduction?**
Simplex method, standard technique in linear programming for solving an optimization problem, typically one involving a function and several constraints expressed as inequalities. The inequalities define a polygonal region, and the solution is typically at one of the vertices. The simplex method is a systematic procedure for testing the vertices as possible solutions.
Principal component analysis, or PCA, is a statistical procedure that allows to summarize the information by means of a smaller set of “summary indices” that can be more easily visualized and analyzed. 
Dimensionality reduction means to reduce the dimensionality of large data sets, by transforming a large set of variables into a smaller one that still contains most of the information in the large set.*References* 



1.	https://www.britannica.com/topic/simplex-method
2.	https://www.sartorius.com/en/knowledge/science-snippets/what-is-principal-component-analysis-pca-and-how-it-is-used-507186
3.	https://builtin.com/data-science/step-step-explanation-principal-component-analysis


**32. Why should I not remove the NA values? What is the difference between NAs and NANs.?**

NA is used to represent missing data of any data type like numeric, text etc. without pointing a particular data type. NA in a code indicates a missing value in a custom way, especially when dealing with non-numerical data. There's no built-in NA data type in Python.
NaN is a special floating-point value in Python that represents "Not a Number." It's a built-in data type specifically used to indicate missing numerical data. Libraries like NumPy and Pandas recognize NaN and provide functions to handle it appropriately in calculations (e.g., functions that ignore NaN during operations)

*References*.
1.	https://www.projectpro.io/recipes/what-is-difference-between-na-and-nan-r
2.	https://www.r-bloggers.com/2012/08/difference-between-na-and-nan-in-r/
3.	https://stackoverflow.com/questions/15496361/what-is-the-difference-between-nan-and-inf-and-null-and-na-in-r


**34. Demonstrate: Create two matrices, multiply them, transverse them, transpose them. What is orthogonality of a matrix?**

Matrix is a data structure where numbers are arranged in rows and columns which arise a two-dimensional data. A matix in python is formed by making a list within a list. But NUMPY package in python allows to create N dimensional arrays objects. Orthogonality is refer to the matrix whose transpose is equal to inverse of the matrix. 

*References*
1. https://www.askpython.com/python/python-matrix-tutorial
2. https://wiki.python.org/moin/BeginnersGuide
3. https://numpy.org/doc/stable/reference/generated/numpy.diagonal.html
4. https://www.cuemath.com/algebra/orthogonal-matrix/
5. https://www.geeksforgeeks.org/check-whether-given-matrix-orthogonal-not/


In [51]:
#creating Matrices 
matrix1 = [[1,5,7],
           [6,0,5]]
print(matrix1)
## it has two row and three columns 
##now creating multideimensional arrays using numpy
import numpy as np
one = np.array([6,7,8])
print (one)
print(type(one))

##creating matrix using martix function in numpy
matriz_1 = np.matrix([[11, 9], [9, 3]])  
print('MatrixA:\n', matriz_1)

matrizB = np.matrix('[10,20;30,40]', dtype=np.int32)  # Setting the data-type to int
print('\nMatrixB:\n', matrizB)
####### multiply two matrices, and the scaler product of the result
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print("product of matrices",C)
print("scalar product:\n", 10*C)
######## Transpose of a matrix 
print("Original Matrix C:\n")
print(C)
print('\nDimensions of the original Matrix C: ',C.shape)
print("\nTranspose of Matrix C:\n ")
res = C.T
print(res)
print('\nDimensions of the Matrix A after performing the Transpose Operation:  ',res.shape)
 ###Transverse of the matrix 
l = C.diagonal(0,0,1)
print("diagonal is",l)

##orthogonality 
ortho = C*res 
print ("ort", ortho)



[[1, 5, 7], [6, 0, 5]]
[6 7 8]
<class 'numpy.ndarray'>
MatrixA:
 [[11  9]
 [ 9  3]]

MatrixB:
 [[10 20]
 [30 40]]
product of matrices [[ 36 -12]
 [ -1   2]]
scalar product:
 [[ 360 -120]
 [ -10   20]]
Original Matrix C:

[[ 36 -12]
 [ -1   2]]

Dimensions of the original Matrix C:  (2, 2)

Transpose of Matrix C:
 
[[ 36  -1]
 [-12   2]]

Dimensions of the Matrix A after performing the Transpose Operation:   (2, 2)
diagonal is [36  2]
ort [[1296   12]
 [  12    4]]
